Repository bSI-InfraRoom/MVD-Infra-Test-Instructions, pull requests merged in 2022-01, with the labels that each got.

#6 Updating of Structure & Templates
  .github/ISSUE_TEMPLATE/dataset_bug_report.md
  .github/ISSUE_TEMPLATE/documentation_bug_report.md
  .github/ISSUE_TEMPLATE/exchange_definition_proposal.md
  .github/ISSUE_TEMPLATE/test_case_definition_proposal.md
  .github/pull_request_template.md
  E1-ALRF/README.md
  E1-AR/README.md
  E10-MTME/README.md
  E1a-ARC/README.md
  E1a-ARSE/README.md
  E1b-ARCT/README.md
  E1b-ARSE/README.md
  E2-AGST/README.md
  E2a-TRST/README.md
  E3-EW/Earthworks Fill (local)/Readme.md
  E3-EW/README.md
  E3-EWKS/README.md
  E4-BRST/README.md
  E5-SIGN/README.md
  E6-ENGY/README.md
  E7-GEOT/README.md
  E8-TECO/README.md
  E9-DNGE/README.md
  README.md
  docs/CONTRIBUTING.md
  docs/XXXX/Dataset/README.md
  docs/XXXX/README.md
Labels: repository

#24 Update README.md
  docs/XXXX/README.md
Labels: bug, repository

#27 Update README.md - small typos
  docs/XXXX/Dataset/README.md
Labels: bug, documentation
